import type { Movement } from "@/components/dashboard/movimientos/MovementsTable";

/**
 * Datos de la maqueta aprobada (web/design/03-movimientos.html), copiados tal
 * cual. Si el componente pinta esto y no se ve como la maqueta, el fallo es del
 * componente. Solo los usa /preview.
 *
 * A diferencia de los otros dos bancos de pruebas, aquí las cantidades, los
 * valores y las fechas van EN CRUDO y no ya formateados: el separador de día,
 * la hora de cada fila y los decimales de cada unidad los tiene que calcular la
 * pantalla, y si el mock los diera hechos no se estaría probando eso.
 *
 * Las cantidades son las que enseña la maqueta, redondeadas a dos decimales.
 * Con los saldos reales (18,9292 JTO · 0,025986 BTC) `tokenAmount` sacaría más
 * decimales, que es lo correcto y lo que hace el Resumen.
 */
export const MOCK_MOVIMIENTOS: Movement[] = [
  {
    id: "m1",
    operation: "Harvest rewards",
    quantity: 18.93,
    symbol: "JTO",
    platform: "Kamino (METEORA)",
    network: "Solana",
    timestamp: "2026-07-12T18:27:00",
    value: 10.05,
    tax: { label: "RCM staking", tone: "taxable" },
  },
  {
    id: "m2",
    operation: "Harvest rewards",
    quantity: 19.86,
    symbol: "PYUSD",
    platform: "Kamino (ORCA)",
    network: "Solana",
    timestamp: "2026-07-12T18:27:00",
    value: 17.37,
    tax: { label: "RCM staking", tone: "taxable" },
  },
  {
    id: "m3",
    operation: "Añadir liquidez",
    quantity: 4840.12,
    symbol: "USDC",
    platform: "Kamino (ORCA)",
    network: "Solana",
    timestamp: "2026-07-12T18:12:00",
    value: 4233.84,
    tax: { label: "Movimiento LP", tone: "taxable" },
  },
  {
    id: "m4",
    operation: "Retirada",
    quantity: 18.93,
    symbol: "JTO",
    platform: "Kamino (METEORA)",
    network: "Solana",
    timestamp: "2026-07-12T18:10:00",
    value: 10.07,
    tax: { label: "GP permuta", tone: "taxable" },
  },
  {
    id: "m5",
    operation: "Depósito",
    quantity: 11.49,
    symbol: "USDC",
    platform: "Wallet",
    network: "Solana",
    timestamp: "2026-07-12T18:10:00",
    value: 10.05,
    tax: { label: "No imponible", tone: "exempt" },
  },
  {
    id: "m6",
    operation: "Depósito",
    quantity: 19.96,
    symbol: "USDC",
    platform: "Wallet",
    network: "Solana",
    timestamp: "2026-07-12T18:09:00",
    value: 17.46,
    tax: { label: "No imponible", tone: "exempt" },
  },
  {
    id: "m7",
    operation: "Retirada",
    quantity: 19.96,
    symbol: "PYUSD",
    platform: "Kamino (ORCA)",
    network: "Solana",
    timestamp: "2026-07-12T18:09:00",
    value: 17.46,
    tax: { label: "Pérdida patrimonial", tone: "taxable" },
  },
  {
    id: "m8",
    operation: "Depósito",
    quantity: 0.03,
    symbol: "SOL",
    platform: "Wallet",
    network: "Solana",
    timestamp: "2026-07-12T18:08:00",
    value: 2.03,
    tax: { label: "No imponible", tone: "exempt" },
  },
  {
    id: "m9",
    operation: "Retirada",
    quantity: 33.41,
    symbol: "SOL",
    platform: "Wallet",
    network: "Solana",
    timestamp: "2026-07-12T18:07:00",
    value: 2259.14,
    tax: { label: "Pérdida patrimonial", tone: "taxable" },
  },
  {
    id: "m10",
    operation: "Depósito",
    quantity: 1692.53,
    symbol: "PYUSD",
    platform: "Kamino (ORCA)",
    network: "Solana",
    timestamp: "2026-07-06T14:46:00",
    value: 1692.2,
    tax: { label: "No imponible", tone: "exempt" },
  },
  {
    id: "m11",
    operation: "Depósito",
    quantity: 1429.17,
    symbol: "USDC",
    platform: "Kamino (ORCA)",
    network: "Solana",
    timestamp: "2026-07-06T14:46:00",
    value: 1428.8,
    tax: { label: "No imponible", tone: "exempt" },
  },
  {
    id: "m12",
    operation: "Depósito",
    quantity: 2.77,
    symbol: "SOL",
    platform: "Wallet",
    network: "Solana",
    timestamp: "2026-07-06T14:47:00",
    value: 240,
    tax: { label: "No imponible", tone: "exempt" },
  },
  {
    id: "m13",
    operation: "Depósito",
    quantity: 0.026,
    symbol: "BTC",
    platform: "Wallet",
    network: "Bitcoin",
    timestamp: "2026-07-06T14:47:00",
    value: 2100,
    tax: { label: "No imponible", tone: "exempt" },
  },
];
