import type { CarteraSectionData } from "@/components/dashboard/cartera/PositionsTable";

/**
 * Datos de la maqueta aprobada (web/design/02-cartera.html), copiados tal cual.
 * Si el componente pinta esto y no se ve como la maqueta, el fallo es del
 * componente. Solo los usa /preview.
 */
export const MOCK_CARTERA: CarteraSectionData[] = [
  {
    key: "lp",
    title: "Liquidity Pools",
    total: "8.973,10 US$",
    count: "· 3 posiciones",
    balanceLabel: "Saldo",
    valueLabel: "Valor actual",
    yieldLabel: "Rendimiento",
    positions: [
      {
        key: "pyusd-usdc",
        symbols: ["pyUSD", "USDC"],
        name: "pyUSD/USDC",
        venue: "Solana · Kamino (ORCA)",
        risk: { position: 52, label: "Rango 0,995 – 1,005 · actual 1,000" },
        balances: ["4.216,61 pyUSD", "3.746,15 USDC"],
        deposited: "7.960,28 US$",
        currentValue: "7.962,11 US$",
        pnl: "+1,83 US$",
        pnlPercent: "+0,02 %",
        pnlTone: "profit",
        yields: [
          { value: "17,35 US$", label: "sin reclamar", strong: true },
          { value: "19,85 US$", label: "cobrado" },
        ],
      },
      {
        key: "jitosol-sol",
        symbols: ["JITOSOL", "SOL"],
        name: "JITOSOL/SOL",
        venue: "Solana · Kamino (METEORA)",
        risk: { position: 26, label: "Rango 1,148 – 1,196 · actual 1,161" },
        balances: ["2,5495 JITOSOL", "5,1244 SOL"],
        deposited: "800,00 US$",
        currentValue: "615,58 US$",
        pnl: "−184,42 US$",
        pnlPercent: "−23,05 %",
        pnlTone: "loss",
        yields: [
          { value: "1,66 US$", label: "sin reclamar", strong: true },
          { value: "11,48 US$", label: "cobrado" },
        ],
      },
      {
        key: "weth-cbbtc",
        symbols: ["WETH", "cbBTC"],
        name: "WETH/cbBTC 0,01 %",
        venue: "Base · PancakeSwap V3",
        // Al borde del rango: el punto pasa a ámbar. Es la excepción, y por eso
        // se señala; si todas las filas lo llevaran, no diría nada.
        risk: {
          position: 94,
          label: "Rango 0,0290 – 0,0355 · actual 0,0354 · al borde",
          atRisk: true,
        },
        balances: ["0,210821 WETH", "0,000003 cbBTC"],
        deposited: "600,00 US$",
        currentValue: "395,41 US$",
        pnl: "−204,59 US$",
        pnlPercent: "−34,10 %",
        pnlTone: "loss",
        yields: [{ value: "9,84 US$", label: "sin reclamar", strong: true }],
      },
    ],
  },
  {
    key: "wallet",
    title: "Hold",
    total: "2.112,27 US$",
    count: "· 5 posiciones",
    balanceLabel: "Saldo",
    valueLabel: "Valor actual",
    positions: [
      {
        key: "btc",
        symbols: ["BTC"],
        name: "BTC",
        venue: "BTC (HOLD) · Bitcoin",
        balances: ["0,025986 BTC"],
        deposited: "2.100,00 US$",
        currentValue: "1.648,79 US$",
        pnl: "−451,21 US$",
        pnlPercent: "−21,49 %",
        pnlTone: "loss",
      },
      {
        key: "usdc",
        symbols: ["USDC"],
        name: "USDC",
        venue: "HyperEVM",
        balances: ["370,02 USDC"],
        deposited: "369,95 US$",
        currentValue: "369,95 US$",
        pnl: "0,00 US$",
        pnlPercent: "0,00 %",
        pnlTone: "flat",
      },
      {
        key: "hype",
        symbols: ["HYPE"],
        name: "HYPE",
        venue: "HyperEVM",
        balances: ["1,589 HYPE"],
        deposited: "80,00 US$",
        currentValue: "86,40 US$",
        pnl: "+6,40 US$",
        pnlPercent: "+8,00 %",
        pnlTone: "profit",
      },
      {
        key: "sol",
        symbols: ["SOL"],
        name: "SOL",
        venue: "Solana",
        balances: ["0,066533 SOL"],
        deposited: "5,14 US$",
        currentValue: "4,87 US$",
        pnl: "−0,27 US$",
        pnlPercent: "−5,34 %",
        pnlTone: "loss",
      },
      {
        key: "weth",
        symbols: ["WETH"],
        name: "WETH",
        venue: "Base",
        balances: ["0,001206 WETH"],
        deposited: "2,11 US$",
        currentValue: "2,26 US$",
        pnl: "+0,15 US$",
        pnlPercent: "+7,19 %",
        pnlTone: "profit",
      },
    ],
  },
  {
    key: "staking",
    title: "Staking",
    total: "1.847,20 US$",
    count: "· 2 posiciones",
    balanceLabel: "Saldo",
    valueLabel: "Valor actual",
    yieldLabel: "Rendimiento",
    positions: [
      {
        key: "jitosol",
        symbols: ["SOL"],
        name: "SOL",
        venue: "Solana · Jito",
        balances: ["11,84 JitoSOL"],
        deposited: "1.950,00 US$",
        currentValue: "1.612,40 US$",
        pnl: "−337,60 US$",
        pnlPercent: "−17,31 %",
        pnlTone: "loss",
        yields: [
          { value: "8,42 US$", label: "sin reclamar", strong: true },
          { value: "34,18 US$", label: "cobrado" },
        ],
      },
      {
        key: "hype-staking",
        symbols: ["HYPE"],
        name: "HYPE",
        venue: "HyperEVM · HyperLiquid",
        balances: ["4,25 HYPE"],
        deposited: "210,00 US$",
        currentValue: "234,80 US$",
        pnl: "+24,80 US$",
        pnlPercent: "+11,81 %",
        pnlTone: "profit",
        yields: [{ value: "1,26 US$", label: "sin reclamar", strong: true }],
      },
    ],
  },
  {
    key: "lending",
    title: "Lending",
    total: "1.284,60 US$",
    count: "· 1 posición",
    balanceLabel: "Colateral y deuda",
    // «Valor actual» pasa a «Valor NETO»: en lending, el valor es el colateral
    // menos la deuda, y llamarlo igual que en un hold engaña.
    valueLabel: "Valor neto",
    yieldLabel: "Interés",
    positions: [
      {
        key: "kamino-lend",
        symbols: ["USDC", "SOL"],
        name: "USDC / SOL",
        venue: "Solana · Kamino Lend",
        risk: { position: 57, label: "Factor de salud 2,14" },
        balances: [],
        lending: {
          collateral: ["1.870,00 USDC", "0,4736 SOL"],
          debt: ["−620,00 USDC"],
        },
        deposited: "1.250,00 US$",
        currentValue: "1.284,60 US$",
        pnl: "+34,60 US$",
        pnlPercent: "+2,77 %",
        pnlTone: "profit",
        yields: [
          { value: "12,40 US$", label: "generado", strong: true },
          { value: "4,85 US$", label: "pagado" },
        ],
      },
    ],
  },
];
